version: '1'
services:
  spring-mircoservices-onlineshop-eureka-server:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    env_file:
      - docker-compose.env
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
    healthcheck:
      test: "curl --fail --silent http://localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
  spring-mircoservices-onlineshop-eureka-client:
    container_name: eureka-client
    build:
      context: eureka-client
      dockerfile: Dockerfile
    image: eureka-client:latest
    env_file:
      - docker-compose.env
    networks:
      - spring-cloud-network
    depends_on:
      spring-mircoservices-onlineshop-eureka-server:
        condition: service_healthy
  spring-mircoservices-onlineshop-api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    env_file:
      - docker-compose.env
    ports:
      - 8081:8081
    networks:
      - spring-cloud-network
    depends_on:
      - spring-mircoservices-onlineshop-eureka-client
networks:
  spring-cloud-network:
    driver: bridge